Fix compiler failure in tapcfg
The string copy of iterface name may be truncated, which is causing an compiler
error here. Fix it.

  In file included from build/lib/tapcfg_unix.c:60,
                   from build/lib/tapcfg.c:31:
  In function 'tapcfg_start_dev',
      inlined from 'tapcfg_start' at build/lib/tapcfg_unix.c:112:11:
  build/lib/tapcfg_unix_linux.h:64:2: error: 'strncpy' output may be truncated copying 15 bytes from a string of length 15 [-Werror=stringop-truncation]
    strncpy(tapcfg->ifname, ifr.ifr_name, sizeof(tapcfg->ifname)-1);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~